# Generated by Django 5.1.4 on 2025-01-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_question_choice_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='Content',
        ),
    ]
