# Generated by Django 5.1.4 on 2025-01-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_rename_text_question_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='Content',
        ),
    ]
